# Generated by Django 4.2 on 2023-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Number')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('date', models.DateField(verbose_name='Date of supply')),
                ('cost_rub', models.FloatField(verbose_name='Cost in RUB')),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
            },
        ),
    ]
